
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const KEY='awakened_final_v2';
const defaultState={onboarded:false,name:'PLAYER',objectives:[],xp:0,totalXP:0,level:1,streak:0,lastAction:'',focusMinutes:0,quests:[],habits:[],journal:[],schedule:[],bosses:[{id:1,title:'MASTER YOUR NEXT GOAL',hp:1000,max:1000}],stats:{Strength:10,Intelligence:10,Discipline:10,Focus:10,Endurance:10,Consistency:10,Knowledge:10,Energy:10},achievements:[],settings:{reducedMotion:false,sound:true,notifications:false}};
let state=Object.assign(structuredClone(defaultState),JSON.parse(localStorage.getItem(KEY)||'{}'));state.stats=Object.assign(defaultState.stats,state.stats||{});let page='home',timer=null,remaining=1500,deferredInstall=null;

const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function need(l){return Math.round(100+50*Math.pow(l,1.35))}
function rank(){return ['E','D','C','B','A','S','SS','SSS'][Math.min(7,Math.floor((state.level-1)/5))]}
function title(){return state.level>=25?'LEGEND':state.level>=15?'ELITE':state.level>=10?'DISCIPLINED':'AWAKENED'}
function award(n,reason=''){state.xp+=n;state.totalXP+=n;let old=state.level;while(state.xp>=need(state.level)){state.xp-=need(state.level);state.level++}save();if(state.level>old){toast('LEVEL UP',`LEVEL ${old} → ${state.level}`);if(state.level%5===0)toast('RANK ANALYSIS',`RANK ${rank()} QUALIFIED`)}else toast('XP GAIN',`+${n} XP${reason?' · '+reason:''}`)}
function toast(t,m){let e=document.createElement('div');e.className='toast';e.innerHTML=`<b>[ ${t} ]</b><div class="muted">${m}</div>`;$('#toastHost').append(e);setTimeout(()=>e.remove(),2800)}
function layout(t,b){$('#pageTitle').textContent=t;$('#content').innerHTML=b}
function setNav(){ $$('.sidebar nav button,.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.page===page)) }
function go(p){page=p;setNav();({home,quests,schedule,focus,habits,bosses,skills,analytics,journal,profile,stats}[p]||home)()}

function home(){
 let n=need(state.level),pct=Math.min(100,state.xp/n*100),done=state.quests.filter(q=>q.done).length,open=state.quests.filter(q=>!q.done);
 layout('COMMAND CENTER',`<div class="grid">
 <div class="card wide"><span class="eyebrow">PLAYER</span><h2>${esc(state.name)}</h2><div class="muted">[${rank()}-RANK | ${title().toUpperCase()}] · LEVEL ${state.level}</div><div class="bar"><i style="width:${pct}%"></i></div><div class="row"><b>${state.xp} XP</b><span class="muted">/ ${n} XP</span><span class="pill">STREAK ${state.streak}</span><span class="pill">TOTAL ${state.totalXP} XP</span></div></div>
 <div class="card"><span class="eyebrow">TODAY</span><div class="stat">${done}/${state.quests.length}</div><div class="muted">quests completed</div><button class="primary" onclick="go('quests')">VIEW QUESTS</button></div>
 <div class="card"><span class="eyebrow">FOCUS</span><div class="stat">${state.focusMinutes}m</div><div class="muted">tracked</div><button class="primary" onclick="go('focus')">START FOCUS</button></div>
 <div class="card wide"><div class="row" style="justify-content:space-between"><span class="eyebrow">ACTIVE MISSIONS</span><button onclick="questModal()">+ CREATE</button></div>${open.slice(0,6).map(questHTML).join('')||'<p class="muted">No active missions detected.</p>'}</div>
 <div class="card"><span class="eyebrow">BOSS</span><h3>${esc(state.bosses[0].title)}</h3><div class="bar"><i style="width:${state.bosses[0].hp/state.bosses[0].max*100}%"></i></div><span class="muted">${state.bosses[0].hp} HP remaining</span></div>
 <div class="card full"><span class="eyebrow">SYSTEM MESSAGE</span><h3>YOUR REAL LIFE IS THE GAME.</h3><p class="muted">Today's actions determine tomorrow's level. Complete one meaningful mission next.</p></div>
 </div>`)
}
function questHTML(q){return `<div class="quest"><button class="check ${q.done?'done':''}" onclick="toggleQuest(${q.id})">${q.done?'✓':'○'}</button><div style="flex:1"><b>${esc(q.title)}</b><div class="muted">${q.cat} · ${q.diff}${q.deadline?' · '+esc(q.deadline):''}</div></div><span class="xp">+${q.xp}</span><button onclick="deleteQuest(${q.id})">×</button></div>`}
function quests(){layout('QUEST DATABASE',`<div class="row" style="justify-content:space-between;margin-bottom:14px"><span class="muted">${state.quests.length} registered missions</span><button class="primary" onclick="questModal()">+ CREATE QUEST</button></div><div class="card full">${state.quests.map(questHTML).join('')||'<p class="muted">No active missions detected.</p>'}</div>`)}
function questModal(){modal(`<span class="eyebrow">QUEST REGISTRATION</span><h2>CREATE MISSION</h2><input id="qtitle" class="field" placeholder="Quest name"><textarea id="qdesc" class="field" rows="3" placeholder="Description"></textarea><div class="option-grid"><select id="qcat" class="field"><option>STUDY</option><option>FITNESS</option><option>PERSONAL</option><option>SKILLS</option><option>DIGITAL</option><option>DISCIPLINE</option><option>CUSTOM</option></select><select id="qdiff" class="field"><option value="5">EASY · 5 XP</option><option value="15">NORMAL · 15 XP</option><option value="30">HARD · 30 XP</option><option value="60">EPIC · 60 XP</option><option value="100">LEGENDARY · 100 XP</option><option value="200">BOSS · 200 XP</option></select></div><input id="qdate" type="date" class="field"><div class="row"><button class="primary" onclick="createQuest()">CREATE QUEST</button><button onclick="closeModal()">CANCEL</button></div>`)}
function createQuest(){let t=$('#qtitle').value.trim();if(!t)return toast('SYSTEM ERROR','Quest name is required.');let d=$('#qdiff');state.quests.push({id:Date.now(),title:t,desc:$('#qdesc').value,cat:$('#qcat').value,diff:d.options[d.selectedIndex].text.split(' ·')[0],xp:+d.value,deadline:$('#qdate').value,done:false,created:new Date().toISOString()});save();closeModal();quests();toast('SYSTEM','QUEST REGISTERED')}
function deleteQuest(id){state.quests=state.quests.filter(q=>q.id!==id);save();quests();toast('SYSTEM','QUEST ARCHIVED')}
function toggleQuest(id){let q=state.quests.find(x=>x.id===id);if(!q||q.done)return;q.done=true;state.streak++;let st=q.cat==='STUDY'?'Intelligence':q.cat==='FITNESS'?'Strength':q.cat==='DISCIPLINE'?'Discipline':'Consistency';state.stats[st]=Math.min(100,state.stats[st]+5);award(q.xp,`+5 ${st}`);if(q.cat==='STUDY'&&!state.achievements.includes('KNOWLEDGE SEEKER')){let count=state.quests.filter(x=>x.done&&x.cat==='STUDY').length;if(count>=5)unlock('KNOWLEDGE SEEKER')}if(state.quests.filter(x=>x.done).length===1)unlock('FIRST STEP');if(state.streak>=7)unlock('UNSTOPPABLE');save();go(page)}
function schedule(){let rows=state.schedule.length?state.schedule.map((x,i)=>`<div class="quest"><b>${esc(x.time)}</b><div style="flex:1"><b>${esc(x.title)}</b><div class="muted">${esc(x.type||'EVENT')}</div></div><button onclick="removeSchedule(${i})">×</button></div>`).join(''):'<p class="muted">No events registered.</p>';layout('SCHEDULE MATRIX',`<div class="grid"><div class="card wide"><div class="row" style="justify-content:space-between"><span class="eyebrow">TIMELINE</span><button class="primary" onclick="scheduleModal()">+ ADD EVENT</button></div>${rows}</div><div class="card"><span class="eyebrow">SMART RULE</span><h3>Reality first.</h3><p class="muted">Keep sleep, school/work and recovery blocks fixed. Place quests around available time instead of creating impossible schedules.</p></div></div>`)}
function scheduleModal(){modal(`<span class="eyebrow">SCHEDULE</span><h2>ADD EVENT</h2><input id="stime" type="time" class="field"><input id="stitle" class="field" placeholder="Event / study block"><select id="stype" class="field"><option>STUDY</option><option>WORK</option><option>FITNESS</option><option>ROUTINE</option><option>BREAK</option><option>OTHER</option></select><div class="row"><button class="primary" onclick="addSchedule()">ADD</button><button onclick="closeModal()">CANCEL</button></div>`)}
function addSchedule(){let t=$('#stitle').value.trim();if(!t)return;state.schedule.push({time:$('#stime').value||'--:--',title:t,type:$('#stype').value});state.schedule.sort((a,b)=>a.time.localeCompare(b.time));save();closeModal();schedule()}
function removeSchedule(i){state.schedule.splice(i,1);save();schedule()}
function focus(){layout('FOCUS MODE',`<div class="card full" style="text-align:center"><span class="eyebrow">FOCUS QUEST</span><div id="timer" class="timer">${fmt(remaining)}</div><div class="row" style="justify-content:center"><button class="primary" onclick="startTimer()">START</button><button onclick="setTimer(1500)">25/5</button><button onclick="setTimer(3000)">50/10</button><button onclick="setTimer(5400)">90/15</button><button onclick="resetTimer()">RESET</button></div><p class="muted">Finish the session to earn XP. Timer state remains on this device while the app is open.</p></div>`)}
function setTimer(s){clearInterval(timer);timer=null;remaining=s;focus()}function startTimer(){if(timer)return;timer=setInterval(()=>{remaining--;if($('#timer'))$('#timer').textContent=fmt(remaining);if(remaining<=0){clearInterval(timer);timer=null;let mins=Math.round(remaining<=0?25:0);state.focusMinutes+=mins;state.stats.Focus=Math.min(100,state.stats.Focus+5);award(25,'Focus');save();toast('FOCUS QUEST COMPLETE','+25 XP · +5 Focus');remaining=1500;focus()}},1000)}function resetTimer(){setTimer(1500)}function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function habits(){layout('HABIT MATRIX',`<div class="grid"><div class="card wide"><div class="row"><input id="habit" class="field" placeholder="New habit"><button class="primary" onclick="addHabit()">ADD</button></div>${state.habits.map((h,i)=>`<div class="quest"><div style="flex:1"><b>${esc(h.name)}</b><div class="muted">Streak ${h.streak||0} · ${h.frequency||'DAILY'}</div></div><button class="pill" onclick="completeHabit(${i})">COMPLETE +5</button><button onclick="removeHabit(${i})">×</button></div>`).join('')||'<p class="muted">No habits registered.</p>'}</div><div class="card"><span class="eyebrow">CONSISTENCY</span><div class="stat">${state.streak}</div><div class="muted">action streak</div></div></div>`)}
function addHabit(){let h=$('#habit').value.trim();if(!h)return;state.habits.push({name:h,streak:0,frequency:'DAILY'});save();habits();toast('SYSTEM','HABIT REGISTERED')}function completeHabit(i){let h=state.habits[i];h.streak=(h.streak||0)+1;state.streak++;state.stats.Consistency=Math.min(100,state.stats.Consistency+3);award(5,'+3 Consistency');save();habits()}function removeHabit(i){state.habits.splice(i,1);save();habits()}
function bosses(){let b=state.bosses[0];layout('BOSS ARENA',`<div class="card full"><span class="eyebrow">LONG-TERM OBJECTIVE</span><h2>${esc(b.title)}</h2><div class="row"><b>HP ${b.hp}</b><span class="muted">/ ${b.max}</span></div><div class="bar"><i style="width:${b.hp/b.max*100}%"></i></div><div class="row"><button class="primary" onclick="damageBoss()">COMPLETE ACTION · -100 HP</button><button onclick="bossModal()">CHANGE BOSS</button></div><p class="muted">Symbolic progression only. Real progress remains yours.</p></div>`)}
function damageBoss(){let b=state.bosses[0];if(b.hp<=0)return;b.hp=Math.max(0,b.hp-100);award(15,'Boss progress');if(b.hp===0){unlock('BOSS SLAYER');toast('BOSS DEFEATED','Reward claimed');}save();bosses()}function bossModal(){modal(`<span class="eyebrow">BOSS CORE</span><h2>SET LONG-TERM GOAL</h2><input id="btitle" class="field" value="${esc(state.bosses[0].title)}"><input id="bhp" type="number" min="100" step="100" class="field" value="${state.bosses[0].max}"><button class="primary" onclick="setBoss()">UPDATE BOSS</button><button onclick="closeModal()">CANCEL</button>`)}function setBoss(){let t=$('#btitle').value.trim(),hp=Math.max(100,+$('#bhp').value||1000);if(t){state.bosses[0]={id:1,title:t,hp,max:hp};save();closeModal();bosses()}}
function skills(){layout('SKILL MATRIX',`<div class="grid">${Object.entries(state.stats).map(([k,v])=>`<div class="card"><span class="eyebrow">SKILL NODE</span><h2>${k}</h2><div class="bar"><i style="width:${Math.min(100,v)}%"></i></div><b>LV ${Math.max(1,Math.floor(v/10))}</b><div class="muted">${v}/100 progression</div></div>`).join('')}</div>`)}
function analytics(){let done=state.quests.filter(q=>q.done).length,total=state.quests.length,rate=total?Math.round(done/total*100):0;layout('ANALYTICS',`<div class="grid"><div class="card"><span class="eyebrow">TOTAL XP</span><div class="stat">${state.totalXP}</div></div><div class="card"><span class="eyebrow">QUEST RATE</span><div class="stat">${rate}%</div></div><div class="card"><span class="eyebrow">FOCUS</span><div class="stat">${state.focusMinutes}m</div></div><div class="card"><span class="eyebrow">STREAK</span><div class="stat">${state.streak}</div></div><div class="card full"><span class="eyebrow">PERFORMANCE</span><div class="heat">${Array.from({length:70},(_,i)=>`<i class="${i%7<Math.min(7,Math.floor(state.totalXP/40))?'on':''}"></i>`).join('')}</div><p class="muted">Activity heatmap is generated from your local progression data.</p></div></div>`)}
function journal(){layout('JOURNAL',`<div class="card full"><span class="eyebrow">PRIVATE LOG</span><textarea id="entry" class="field" rows="6" placeholder="What did you complete? What did you learn? How was your day?"></textarea><button class="primary" onclick="saveJournal()">SAVE ENTRY</button>${state.journal.map(e=>`<div class="quest"><div><b>${esc(e.date)}</b><div class="muted">${esc(e.text)}</div></div></div>`).join('')||'<p class="muted">No entries yet.</p>'}</div>`)}
function saveJournal(){let t=$('#entry').value.trim();if(!t)return;state.journal.unshift({date:new Date().toLocaleString(),text:t});save();journal();toast('SYSTEM','JOURNAL ENTRY SAVED')}
function profile(){layout('PLAYER PROFILE',`<div class="grid"><div class="card wide"><span class="eyebrow">PLAYER ID</span><h2>${esc(state.name)}</h2><p class="muted">[${rank()}-RANK] · LEVEL ${state.level}</p><div class="row"><span class="pill">TITLE ${title()}</span><span class="pill">STREAK ${state.streak}</span><span class="pill">${state.achievements.length} ACHIEVEMENTS</span></div></div><div class="card"><span class="eyebrow">SETTINGS</span><button onclick="settingsModal()">SYSTEM SETTINGS</button><button onclick="exportData()">EXPORT DATA</button></div><div class="card full"><span class="eyebrow">PLAYER CONFIGURATION</span><div class="row"><input id="playerName" class="field" value="${esc(state.name)}"><button class="primary" onclick="setName()">UPDATE NAME</button></div></div><div class="card full"><span class="eyebrow">ACHIEVEMENTS</span>${state.achievements.map(a=>`<span class="pill" style="margin:4px">${esc(a)}</span>`).join('')||'<span class="muted">No achievements unlocked yet.</span>'}</div></div>`)}
function setName(){let n=$('#playerName').value.trim();if(n){state.name=n.toUpperCase();save();profile();toast('SYSTEM','PLAYER PROFILE UPDATED')}}
function settingsModal(){modal(`<span class="eyebrow">SYSTEM SETTINGS</span><h2>CONTROL CENTER</h2><label class="row"><input id="notif" type="checkbox" ${state.settings.notifications?'checked':''}> Notifications (permission required)</label><label class="row"><input id="sound" type="checkbox" ${state.settings.sound?'checked':''}> Sound effects</label><label class="row"><input id="reduce" type="checkbox" ${state.settings.reducedMotion?'checked':''}> Reduced motion</label><button class="primary" onclick="saveSettings()">SAVE SETTINGS</button><button class="danger" onclick="resetSystem()">RESET LOCAL SYSTEM</button><button onclick="closeModal()">CANCEL</button>`)}
function saveSettings(){state.settings.notifications=$('#notif').checked;state.settings.sound=$('#sound').checked;state.settings.reducedMotion=$('#reduce').checked;save();if(state.settings.notifications&&'Notification'in window&&Notification.permission==='default')Notification.requestPermission();closeModal();profile();toast('SYSTEM','SETTINGS UPDATED')}
function exportData(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='system-awakened-data.json';a.click();URL.revokeObjectURL(a.href)}
function resetSystem(){if(confirm('Reset all local SYSTEM: AWAKENED data?')){localStorage.removeItem(KEY);location.reload()}}
function stats(){skills()}
function core(){let open=state.quests.filter(q=>!q.done).sort((a,b)=>b.xp-a.xp).slice(0,3);modal(`<span class="eyebrow">SYSTEM CORE</span><h2>DAILY ADAPTATION</h2><p class="muted">Local assistant: uses your registered quests and schedule on this device. No AI service is being falsely claimed.</p><div class="card">${open.map((q,i)=>`<b>${i+1}. ${esc(q.title)}</b><div class="muted">${q.xp} XP · ${q.diff}</div>`).join('<hr>')||'No open quests. Create a mission.'}</div><button class="primary" onclick="closeModal()">ACKNOWLEDGE</button>`)}
function unlock(name){if(!state.achievements.includes(name)){state.achievements.push(name);save();toast('ACHIEVEMENT UNLOCKED',name)}}
function modal(html){$('#modal').innerHTML=`<div class="dialog">${html}</div>`;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}
$$('[data-page]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));$('#coreBtn').onclick=core;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
Object.assign(window,{go,questModal,createQuest,deleteQuest,toggleQuest,scheduleModal,addSchedule,removeSchedule,startTimer,setTimer,resetTimer,addHabit,completeHabit,removeHabit,damageBoss,bossModal,setBoss,saveJournal,setName,settingsModal,saveSettings,exportData,resetSystem,closeModal});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('#installBtn').classList.remove('hidden');$('#installBtn').onclick=()=>{deferredInstall.prompt();deferredInstall=null;$('#installBtn').classList.add('hidden')}});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});

function showOnboarding(){
 const el=$('#onboarding');el.classList.remove('hidden');el.innerHTML=`<div class="dialog"><span class="eyebrow">INITIALIZATION</span><h2>ENTER YOUR NAME</h2><input id="obName" class="field" placeholder="Player name"><p class="muted">Select your primary objectives.</p><div class="option-grid">${['STUDY','FITNESS','DISCIPLINE','CAREER','SKILLS','PERSONAL GROWTH'].map(x=>`<button class="option" data-obj="${x}">${x}</button>`).join('')}</div><button class="primary" onclick="finishOnboarding()">AWAKEN SYSTEM</button><button onclick="finishOnboarding(true)">SKIP</button></div>`;
 $$('#onboarding .option').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));
}
function finishOnboarding(skip=false){if(!skip){state.name=($('#obName').value.trim()||'PLAYER').toUpperCase();state.objectives=$$('#onboarding .option.selected').map(x=>x.dataset.obj);if(!state.quests.length){state.quests=[{id:Date.now()+1,title:'Complete your first mission',cat:'PERSONAL',diff:'EASY',xp:25,done:false},{id:Date.now()+2,title:'25 minute focused session',cat:'STUDY',diff:'NORMAL',xp:35,done:false}];state.bosses=[{id:1,title:state.objectives[0]?`MASTER ${state.objectives[0]}`:'MASTER YOUR NEXT GOAL',hp:1000,max:1000}]}}state.onboarded=true;save();$('#onboarding').classList.add('hidden');go('home')}
function boot(){let logs=['[SYSTEM BOOTING...]','[INITIALIZING PLAYER DATABASE...]','[LOADING PROGRESSION ENGINE...]','[CALIBRATING HUD...]','[SYSTEM ONLINE]'],i=0;let iv=setInterval(()=>{$('#bootlog').textContent+=logs[i]+'\n';i++;if(i>=logs.length){clearInterval(iv);setTimeout(()=>{$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');state.onboarded?go('home'):showOnboarding()},350)}},420);$('#skipBoot').onclick=()=>{clearInterval(iv);$('#boot').classList.add('hidden');$('#app').classList.remove('hidden');state.onboarded?go('home'):showOnboarding()}}
boot();
